signIn_function_create
waderaku/pomodoro-timer pull request #1
Opened 2022-08-07 13:32 UTC by kobayashi1227

signIn画面の作成。
SignUpの導線管理。
![image](https://user-images.githubusercontent.com/64314253/183293288-92542989-3c4e-46ca-8d5e-0aaf7e9b63b1.png)

2022-08-07 14:35 UTC, waderaku commented on frontend/src/domain/model.ts
> +export type SignInOrUpFlag = boolean;
この命名じゃTrueの場合どっちか分からんです。。。

2022-08-07 14:35 UTC, waderaku commented on frontend/src/component/Root.tsx
> +  const { token } = useUserViewModel();
このtokenってテスト用なん？普通に今後も使われる奴じゃない？
後isSigninは？

2022-08-07 14:35 UTC, waderaku commented on frontend/src/component/SignField/SignInFeild/SignInFeild.tsx
> +import {
Fieldって命名だと入力エリアを指してるイメージがあるのは僕だけ？ｗ

2022-08-07 14:35 UTC, waderaku commented on frontend/src/domain/hooks/userViewModel.ts
> +  const toSignIn = () => {
SignOutする導線って存在してる？（Headerにボタンかな）
Token失効したら絶望しそう

2022-08-11 15:51 UTC, kobayashi1227 commented on frontend/src/component/SignField/SignInFeild/SignInFeild.tsx
> +import {
僕的にはあんまり違和感なかったけど…直しました

2022-08-11 15:51 UTC, kobayashi1227 commented on frontend/src/component/Root.tsx
> +  const { token } = useUserViewModel();
なおしたー

2022-08-11 16:27 UTC, kobayashi1227 commented on frontend/src/domain/model.ts
> +export type SignInOrUpFlag = boolean;
直しましたー

2022-08-11 16:28 UTC, kobayashi1227 commented on frontend/src/domain/hooks/userViewModel.ts
> +  const toSignIn = () => {
Headerじゃないかな？
そしてそれ作るのって？タスクないのタスクなの？
そうなら作るけど…

2022-08-11 16:34 UTC, kobayashi1227 commented on frontend/src/domain/hooks/userViewModel.ts
> +  const toSignIn = () => {
あ、Token切れたらどうするのってことか…
Tokenの失効どう検知しようか？
tokenでaccessdinedしたらtokenの中身clearするとか？

2022-08-11 16:37 UTC, kobayashi1227 commented on frontend/src/domain/hooks/userViewModel.ts
> +  const toSignIn = () => {
clearする関数は作っておいたわ

2022-08-13 06:48 UTC, waderaku requested changes

2022-08-13 06:48 UTC, waderaku commented on frontend/src/domain/hooks/userViewModel.ts
> +    console.log(get(aouthTokenState));
console.log警察召喚！

2022-08-13 06:48 UTC, waderaku commented on frontend/src/domain/model.ts
> +export type isUserSignInFlag = boolean;
流石に命名ｗｗｗ
isSignedInとかになるのかな？（過去形=ログイン済み）
ちなみに「is」の時点で「～である」という状態をさす=booleanであることは分かるからFlgはつけなくていいと思うよ（僕も散々命名文句言われてるんですけどね）

2022-08-13 06:48 UTC, waderaku commented on frontend/src/component/SignArea/SignInArea/SignInFeild.tsx
> +                log in
ここもsign inに統一しちゃっていいかもね
どうでもいいけどloginじゃねって思ったけど動詞だとlog inなんだ
https://eigonokoto.com/login-log-in/3306/#toc2

2022-08-15 12:53 UTC, kobayashi1227 commented on frontend/src/domain/model.ts
> +export type isUserSignInFlag = boolean;
isSignedInは直した
Flgは命名かぶっちゃうからつけてる(許してほしい)

2022-08-15 13:04 UTC, kobayashi1227 commented on frontend/src/domain/model.ts
> +export type isUserSignInFlag = boolean;
ごめんなさい僕が愚かでした

2022-08-15 13:05 UTC, kobayashi1227 commented on frontend/src/component/SignArea/SignInArea/SignInFeild.tsx
> +                log in
直しましたー

2022-08-15 13:05 UTC, kobayashi1227 commented on frontend/src/domain/hooks/userViewModel.ts
> +    console.log(get(aouthTokenState));
直しました

2022-08-15 13:09 UTC, waderaku approved these changes

2022-08-15 13:14 UTC, yotaro-shimose approved these changes

2022-08-15 13:18 UTC, merged