Feature/folder structure
waderaku/pomodoro-timer pull request #10
Opened 2022-08-26 16:10 UTC by yotaro-shimose

![Screenshot from 2022-08-27 01-09-58](https://user-images.githubusercontent.com/65691831/186947719-98e8f72a-19be-44e2-b45a-69d37512895d.png)

2022-08-26 16:11 UTC, yotaro-shimose commented
コミットレベルでの差分に注目することを進めます。１個めが地獄。

2022-08-26 16:31 UTC, yotaro-shimose commented
![Screenshot from 2022-08-27 01-31-13](https://user-images.githubusercontent.com/65691831/186950981-2f961c97-4c3d-4541-bafe-3f8feae5ae3b.png)

2022-08-26 16:43 UTC, yotaro-shimose commented
- バックエンドの中にCDKがあったのを直して、プロジェクトルートの中にfront, back, infraが並列して存在するようにしました。
- presentationレイヤのcontrollerフォルダをchaliceフォルダに改名しました。chaliceのcontrollerが置かれる予定です。同じ階層にfastapi/register_event.pyみたいにいろんなpresentationレイヤを配置できる感じにしたいです。
- 基本的にはプロジェクトルートから作業することを想定しています。cdk deployもプロジェクトルートから実行することが想定されています。（適切なコマンドをうてばinfrastructureからでもうてます)。同様にbackendからでもデバッグが実行できます。プロジェクトルートで作業（推奨）するためにはsettings.jsonに次を記載するか、下瀬のコンテナの最新版をpullしてください。
```json
{
  "[python]": {
    "editor.tabSize": 4,
    "editor.detectIndentation": false,
    "editor.formatOnSave": true
  },
  "python.linting.enabled": true,
  "python.linting.pylintEnabled": false,
  "python.linting.flake8Enabled": true,
  "python.linting.lintOnSave": true,
  "python.formatting.provider": "black",
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.organizeImports": true
  },

  "python.testing.unittestEnabled": false,
  "python.testing.pytestEnabled": true,
  "python.testing.cwd": "${workspaceFolder}/backend/test",
  "python.linting.flake8Args": [
    "--max-line-length=88",
    "--ignore=E203,W503,W504"
  ]
}
```

DockerをPullしてきた場合、実行コマンドはdiscordのgeneralチャンネルに以前はった以下のコマンドを利用することに注意してください。

```bash
docker run --name=pomodoro -v /var/run/docker.sock:/var/run/docker.sock --net=pomodoro-timer -it -d yosemat/pomodoro:latest
```

2022-08-27 01:16 UTC, waderaku commented
lambdaいないんご
![image](https://user-images.githubusercontent.com/64270877/187008618-8e11c0ac-492f-451f-8c8f-7e1f6348e380.png)

2022-08-27 01:16 UTC, waderaku commented
何か前も話した気がするけど、cdklibはchalice側の制約で、デプロイされるリソースはapp.pyとchalicelib直下のファイルだけのはず

2022-08-27 01:18 UTC, waderaku requested changes
何か前も話した気がするけど、cdklibはchalice側の制約で、デプロイされるリソースはapp.pyとchalicelib直下のファイルだけのはず

2022-08-27 04:21 UTC, yotaro-shimose commented
僕上にcdk deploy成功の写真貼ったと思うんだけど、これではdeployできたとはいえなさそう？僕はChaliceがフォルダ階層の制約をつけるのはおかしいとおもうのでchalicelib直下の件ソースほしい。
lambdaがいないのは僕がcdk destroyしたからだと思う。lambdaに限らずdynamodbも何もかもいないんじゃないかな。

2022-08-27 04:32 UTC, yotaro-shimose commented
あれかな、写真では一見するとlambda出来上がってるように見えるけど、APIハンドラーは出来上がったもののlambdaはできあがってないみたいな感じかな。chalicelibじゃないとだめなのかなやっぱり。

その場合はchalicelibにpresentationだけ置くことにしようと思っている。

2022-08-27 04:35 UTC, yotaro-shimose commented
source 見つけた
https://aws.github.io/chalice/topics/packaging.html

2022-08-27 05:07 UTC, waderaku commented
app.py以外のあらゆるソースコードがchalicelibにいないとダメなんじゃなかったっけ？
多分そのリンク先に書いてあったと思うけど
cdk deploy自体が成功したように見えるのはapp.py(+requirements.txtに記載している各ライブラリ)だけがデプロイされてるんだと思う

2022-08-27 05:30 UTC, waderaku commented
ちなみになんでかよくわからんけどDynamoDBだけは破壊されてなかった
だから僕さっき改めてchalice deployしようとしたんだけどalready exists って怒られた

2022-08-27 12:41 UTC, yotaro-shimose commented
なるほどね。そういやdbは破壊時のpolicyを明示的にに書かないとデフォルトでは安全のために破壊されないみたい。

とはいえnumpyみたいに任意のサードパーティライブラリを読み込むことができるからそういう方針でデプロイするのが綺麗な気がする。
ライブラリ全体がChaliceに依存するのはddd的に楽しくないよね。

2022-08-27 14:31 UTC, waderaku commented
このアプリケーションのフレームワークに依存していない部分はただchalicelib直下に配置されているだけだからChaliceに依存しているとは思ってないけどね。
他に持ってく時は丸ごと持っていけばいいだけだし。
だからやっても良いけど、ほぼ自動化されてないと嫌かな（面倒だしいっかなと思ってるけど）

2022-09-19 06:56 UTC, closed without merging